<a href="https://colab.research.google.com/github/AranyaJ633021028/BasicProg_DataViz65/blob/main/Recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Slicing

In [1]:
import numpy

In [2]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [3]:
import numpy as np

In [4]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

# Quiz 2
1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [5]:
#slice ค่าลบออกมาจาก mat_b
mat_b[:4,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [6]:
#slice [1,2,3] จาก mat_a
mat_a[1,:3]

array([1, 2, 3])

In [7]:
#slice [[1,3],[9,7],[3,9]] ออกมาจาก mat_b
mat_b[1:4,2:5:2]

array([[1, 3],
       [9, 7],
       [3, 9]])